// This file is generated by npm run sync:releases. Do not edit by hand.
import type { HardwareSchema } from "./types";

import release_26_3 from "./data/releases/26.3.json";
import release_25_10 from "./data/releases/25.10.json";
import release_25_7 from "./data/releases/25.7.json";

export const bundledReleaseSchemas: Record<string, HardwareSchema> = {
  "26.3": release_26_3 as HardwareSchema,
  "25.10": release_25_10 as HardwareSchema,
  "25.7": release_25_7 as HardwareSchema,
};

