// This file is generated by npm run sync:releases. Do not edit by hand.
import type { HardwareSchema } from "./types";

import release_srsim_26_3 from "./data/releases/srsim-26.3.json";
import release_srsim_25_10 from "./data/releases/srsim-25.10.json";
import release_srsim_25_7 from "./data/releases/srsim-25.7.json";
import release_sros_26_3 from "./data/releases/sros-26.3.json";
import release_sros_25_10 from "./data/releases/sros-25.10.json";
import release_sros_25_7 from "./data/releases/sros-25.7.json";

export const bundledReleaseSchemas: Record<string, HardwareSchema> = {
  "srsim:26.3": release_srsim_26_3 as HardwareSchema,
  "srsim:25.10": release_srsim_25_10 as HardwareSchema,
  "srsim:25.7": release_srsim_25_7 as HardwareSchema,
  "sros:26.3": release_sros_26_3 as HardwareSchema,
  "sros:25.10": release_sros_25_10 as HardwareSchema,
  "sros:25.7": release_sros_25_7 as HardwareSchema,
};
